server:
  port: 8061

spring:
  output:
    ansi:
      enabled: always
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=5m

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"
