server:
  port: 8060
  forward-headers-strategy: framework

spring:
  output:
    ansi:
      enabled: always
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=5m
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay=
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
          filters:
            - RewritePath=/department/(?<path>.*), /$\{path}
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost/realms/demo/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost/realms/demo
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: IWLSnakHG8aNTWNaWuSj0a11UY4lzxd9
            authorization-grant-type: authorization_code
            scope: openid

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

springdoc:
  cache:
    disabled: true
  version: "@springdoc.version@"
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"
