spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
server:
  port: 0
spring:
  application:
    name: department-service
  cloud:
    config:
      enabled: false
springdoc:
  packagesToScan: dev.hobie.department
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:pwd@localhost:8061/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
