spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8088"
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
logging:
  level:
    root: info
    web: debug
    dev.hobie.gateway_service: debug
