spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
server:
  port: 8061
spring:
  application:
    name: discovery-service
  cloud:
    config:
      enabled: false
  security:
    user:
      name: admin
      password: pwd
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    root: info
    web: debug
    org.springframework.security: debug
    dev.hobie.discoveryservice: debug
