spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker
---
server:
  port: 0
spring:
  application:
    name: organization-service
  config:
    import: "optional:configserver:http://localhost:8088"
