server:
  port: 8088

spring:
  application:
    name: @project.name@
  profiles:
    active: native
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USER}
    password: ${SPRING_RABBITMQ_PASS}

encrypt:
  key: ${ENCRYPT_KEY}

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"
  level:
    root: info
    web: trace
    dev.hobie.config: trace
